import { allocateAddress, isWithin } from './wireguard.ts';

export type NodeRole = 'control-plane' | 'worker';

export interface ClusterNode {
  name: string;
  /** Public address the control plane reaches it on. */
  ip: string;
  /** Mesh address. Allocated, never typed by hand. */
  wireguardIp: string;
  role: NodeRole;
}

export interface ClusterSettings {
  brand: string;
  wireguardCidr: string;
  wireguardPort: number;
  k3sVersion: string;
  sshUser: string;
  sshKey: string;
}

export const DEFAULT_SETTINGS: ClusterSettings = {
  brand: 'simbkit',
  wireguardCidr: '10.89.0.0/24',
  wireguardPort: 51820,
  k3sVersion: 'v1.34.1+k3s1',
  sshUser: 'root',
  sshKey: '~/.ssh/id_ed25519',
};

const NAME_RE = /^[a-z]([-a-z0-9]*[a-z0-9])?$/;

/** Next node name in the `<brand>-wk-NN` series, skipping names already used. */
export function nextNodeName(brand: string, role: NodeRole, existing: readonly ClusterNode[]): string {
  const kind = role === 'control-plane' ? 'cp' : 'wk';
  const used = new Set(existing.map((n) => n.name));
  for (let i = 1; i < 1000; i++) {
    const name = `${brand}-${kind}-${String(i).padStart(2, '0')}`;
    if (!used.has(name)) return name;
  }
  throw new Error('exhausted node names');
}

export interface AddNodeInput {
  ip: string;
  role?: NodeRole;
  name?: string;
}

/** Place a new node in the cluster: allocate its address, name it, validate it. */
export function addNode(
  nodes: readonly ClusterNode[],
  input: AddNodeInput,
  settings: ClusterSettings = DEFAULT_SETTINGS,
): ClusterNode {
  const role = input.role ?? (nodes.some((n) => n.role === 'control-plane') ? 'worker' : 'control-plane');

  if (role === 'control-plane' && nodes.some((n) => n.role === 'control-plane')) {
    // k3s HA needs an embedded etcd or an external datastore and a load balancer
    // in front of the API. Pretending a second server "just joins" produces a
    // split cluster, so refuse rather than half-support it.
    throw new Error(
      'a control plane already exists; multi-master k3s needs an HA datastore and is not supported here',
    );
  }
  if (nodes.some((n) => n.ip === input.ip)) {
    throw new Error(`${input.ip} is already in the cluster`);
  }

  const name = input.name ?? nextNodeName(settings.brand, role, nodes);
  if (!NAME_RE.test(name)) {
    throw new Error(`"${name}" is not a valid node name (lowercase letters, digits and hyphens)`);
  }
  if (nodes.some((n) => n.name === name)) throw new Error(`node name "${name}" is taken`);

  const wireguardIp = allocateAddress(
    settings.wireguardCidr,
    nodes.map((n) => n.wireguardIp),
  );

  return { name, ip: input.ip, wireguardIp, role };
}

/**
 * Render `cluster/inventory.env`.
 *
 * The three worker lists are positional, so they are built from one traversal —
 * the only way they can be index-aligned by construction rather than by care.
 */
export function renderInventory(nodes: readonly ClusterNode[], settings: ClusterSettings = DEFAULT_SETTINGS): string {
  const control = nodes.find((n) => n.role === 'control-plane');
  if (!control) throw new Error('cluster has no control plane');

  const workers = nodes.filter((n) => n.role === 'worker');
  for (const node of nodes) {
    if (!isWithin(settings.wireguardCidr, node.wireguardIp)) {
      throw new Error(`${node.name} has ${node.wireguardIp}, outside ${settings.wireguardCidr}`);
    }
  }

  const B = settings.brand.toUpperCase();
  return [
    '# GENERATED by the control plane. Edit there, not here.',
    '# Committed so the cluster can be rebuilt from this repository alone.',
    '',
    `${B}_SSH_USER=${settings.sshUser}`,
    `${B}_SSH_KEY=${settings.sshKey}`,
    '',
    `${B}_CONTROL_PLANE_IP=${control.ip}`,
    `${B}_CONTROL_PLANE_NAME=${control.name}`,
    `${B}_CONTROL_PLANE_WG_IP=${control.wireguardIp}`,
    '',
    `${B}_WORKER_IPS="${workers.map((w) => w.ip).join(' ')}"`,
    `${B}_WORKER_NAMES="${workers.map((w) => w.name).join(' ')}"`,
    `${B}_WORKER_WG_IPS="${workers.map((w) => w.wireguardIp).join(' ')}"`,
    '',
    `${B}_WG_CIDR=${settings.wireguardCidr}`,
    `${B}_WG_PORT=${settings.wireguardPort}`,
    `${B}_K3S_FLANNEL_IFACE=wg0`,
    `${B}_K3S_VERSION=${settings.k3sVersion}`,
    '',
  ].join('\n');
}

/**
 * Adding a node re-runs the mesh bootstrap across the whole fleet, which
 * restarts `wg-quick` on every existing node. Brief, but it is a real
 * interruption and the operator should be told before it happens, not after.
 */
export function disruptionWarning(nodes: readonly ClusterNode[]): string | null {
  if (nodes.length === 0) return null;
  return (
    `Adding a node rebuilds the WireGuard mesh on all ${nodes.length} existing node(s). ` +
    'Each one restarts wg-quick@wg0, so in-flight cluster traffic pauses for a few seconds.'
  );
}
