services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.20.2
    restart: unless-stopped
    depends_on:
      - umami-postgres
    environment:
      DATABASE_URL: postgresql://umami:umami_dev_pwd@umami-postgres:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET:-umami_dev_secret}
    ports:
      - '${UMAMI_HOST_PORT:-3030}:3000'

  umami-postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami_dev_pwd
      POSTGRES_DB: umami
    volumes:
      - umami-data:/var/lib/postgresql/data

volumes:
  umami-data:
